version: "2"
services:
 mongo:
  image: mongo:4.2.0
  container_name: mongo
  ports:
   - "27017:27017"
  volumes:
   - ../netflux/data:/data/db:rw
 netflux:
  container_name: netflux
  build: .
  restart: on-failure
  ports:
   - 80:3000
  depends_on:
   - mongo
  env_file:
   - .env
